[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pipforester"
dynamic = ["version"]
description = "A tool to analyze the dependency graph of a pip package."
readme = "README.md"
license = "BSD-2-Clause"
license-files = ["LICENSE.md"]
keywords = ["pip", "graph", "analysis"]
authors = [
  {name = "Jens Klein et al", email = "jk@kleinundpartner.at" }
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "click",
    "networkx",
    "pipdeptree",
    "pygraphviz",
]

[project.urls]
Homepage = "https://github.com/collective/pipforester"
Repository = "https://github.com/collective/pipforester"
Changelog = "https://github.com/collective/pipforester/blob/main/CHANGES.md"
Issues = "https://github.com/collective/pipforester/issues"

[project.scripts]
pipforester = "pipforester:main"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "coverage[toml]>=7.0",
]

[tool.hatch.build.targets.wheel]
packages = ["pipforester"]

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version" }
fallback-version = "0.0.0.dev0"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
parallel = true
source = ["pipforester"]
relative_files = true

[tool.coverage.report]
show_missing = true
fail_under = 65
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
    "A",
    "B",
    "C4",
    "C901",
    "E",
    "F",
    "I",
    "RUF",
    "SIM",
    "T20",
    "UP",
    "W",
]
ignore = [
    "E501",
    "RUF001",
    "RUF002",
]

[tool.ruff.lint.isort]
force-single-line = true
from-first = true
lines-after-imports = 2
lines-between-types = 1
no-sections = true
order-by-type = false

[tool.ruff.lint.mccabe]
max-complexity = 13

[tool.ruff.lint.pycodestyle]
max-line-length = 120
max-doc-length = 120

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["T201"]
